-- Akira Studio Supabase Database Schema
-- Single Admin User Model

-- 1. Portfolio Table
CREATE TABLE public.portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    client TEXT,
    year TEXT,
    description TEXT,
    image_url TEXT,
    video_url TEXT,
    social_url TEXT,
    platform TEXT,
    size TEXT DEFAULT 'medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Services Table
CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Bookings Table
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    company TEXT,
    service_requested TEXT NOT NULL,
    date TEXT,
    budget TEXT,
    status TEXT DEFAULT 'Pending',
    message TEXT,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Customers (Logos) Table
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Testimonials Table
CREATE TABLE public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    company_role TEXT NOT NULL,
    testimonial_text TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Settings (Social Links) Table
-- Since it's a single admin, we can store global key-value settings here.
CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Default Settings
INSERT INTO public.settings (setting_key, setting_value)
VALUES 
(
  'social_links', 
  '[{"platform": "Instagram", "url": "https://instagram.com/aki_akuna"}, {"platform": "TikTok", "url": "https://tiktok.com/@akuna844"}, {"platform": "WhatsApp", "url": "https://wa.me/251923808551"}]'::jsonb
);

-- RLS Setup (Row Level Security)
-- Assuming only the authenticated admin can edit, but anyone can read (except bookings).

ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Public Read Access Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.portfolio FOR SELECT USING (true);
CREATE POLICY "Public services are viewable by everyone." ON public.services FOR SELECT USING (true);
CREATE POLICY "Public customers are viewable by everyone." ON public.customers FOR SELECT USING (true);
CREATE POLICY "Public testimonials are viewable by everyone." ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Public settings are viewable by everyone." ON public.settings FOR SELECT USING (true);

-- Admin Full Access Policies (requires authenticated user)
CREATE POLICY "Admin can do everything on portfolio." ON public.portfolio USING (auth.role() = 'authenticated');
CREATE POLICY "Admin can do everything on services." ON public.services USING (auth.role() = 'authenticated');
CREATE POLICY "Admin can do everything on bookings." ON public.bookings USING (auth.role() = 'authenticated');
CREATE POLICY "Admin can do everything on customers." ON public.customers USING (auth.role() = 'authenticated');
CREATE POLICY "Admin can do everything on testimonials." ON public.testimonials USING (auth.role() = 'authenticated');
CREATE POLICY "Admin can do everything on settings." ON public.settings USING (auth.role() = 'authenticated');

-- Public Insert Access for Bookings
CREATE POLICY "Anyone can submit a booking." ON public.bookings FOR INSERT WITH CHECK (true);
