-- 7. Blogs Table
CREATE TABLE public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    image_url TEXT,
    status TEXT DEFAULT 'Draft',
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);

-- RLS for Blogs
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public blogs are viewable by everyone." ON public.blogs FOR SELECT USING (status = 'Published');
CREATE POLICY "Admin can do everything on blogs." ON public.blogs FOR ALL USING (auth.role() = 'authenticated' OR true); -- Permissive for now as requested earlier

-- Add some seed data
INSERT INTO public.blogs (title, category, excerpt, status, views, image_url, published_at)
VALUES 
('The Art of Voice Acting: Breathing Techniques', 'Acting Tips', 'Discover the fundamental breathing exercises that will give your voice power and consistency in the booth.', 'Published', 1842, 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80', now()),
('Behind the Scenes: National Bank Commercial', 'Behind the Scenes', 'A look into the 3-day shoot for the latest bank campaign and the deep preparation involved.', 'Published', 1204, 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=800&q=80', now()),
('Building a Personal Brand in Ethiopia', 'Industry Insights', 'My journey of growing an audience on TikTok and Instagram while maintaining authenticity.', 'Published', 3015, 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80', now());
